//! AUTO-GENERATED by scripts/generate_gradients.py — DO NOT EDIT MANUALLY
//!
//! Generated: 2026-06-05T21:28:24Z
//!
//! Analytical gradients for the FSRS model (21 parameters).
//! Mathematically equivalent to Burn's dynamic autodiff backward pass.
//!
//! The functions below implement per-step Jacobians for the FSRS state
//! transition equations and a full BPTT (backpropagation through time) loop.

#![allow(
    clippy::excessive_precision,
    clippy::many_single_char_names,
    clippy::too_many_lines,
    unused_variables,
    unused_assignments,
    unused_parens,
    non_snake_case
)]

/// Constants matching simulation.rs
const S_MIN: f32 = 0.001;
const S_MAX: f32 = 36500.0;
const D_MIN: f32 = 1.0;
const D_MAX: f32 = 10.0;

/// Result of a single BPTT step: forward values + Jacobians + parameter grads.
#[derive(Debug, Clone)]
pub struct StepGrads {
    pub s_new: f32,
    pub d_new: f32,
    pub ds_ds: f32,       // ∂S_new/∂S_prev
    pub ds_dd: f32,       // ∂S_new/∂D_prev
    pub dd_dd: f32,       // ∂D_new/∂D_prev (note: ∂D/∂S = 0 always)
    pub ds_dw: [f32; 21], // ∂S_new/∂w[i]
    pub dd_dw: [f32; 21], // ∂D_new/∂w[i]
}

impl StepGrads {
    /// Passthrough step (padding, rating == 0): no state change.
    fn passthrough(s: f32, d: f32) -> Self {
        Self {
            s_new: s,
            d_new: d,
            ds_ds: 1.0,
            ds_dd: 0.0,
            dd_dd: 1.0,
            ds_dw: [0.0; 21],
            dd_dw: [0.0; 21],
        }
    }
}

// ═══════════════════════════════════════════════════════════
// Generated mathematical functions (SymPy + CSE optimized)
// ═══════════════════════════════════════════════════════════

/// Power forgetting curve R(t, S) and its gradients.
/// Returns (R, dR/dS, dR/dw20)
fn forgetting_curve_grad(w: &[f32; 21], t: f32, s: f32) -> (f32, f32, f32) {
    let x0: f32 = (1.0_f32 / s);
    let x1: f32 = (9.0_f32 / 10.0_f32).ln() / w[20];
    let x2: f32 = (-x1).exp();
    let x3: f32 = t * (x2 - 1.0_f32);
    let x4: f32 = x0 * x3 + 1.0_f32;
    let x5: f32 = x4.powf(-w[20]);
    let x6: f32 = (1.0_f32 / x4);

    let r_val: f32 = x5;
    let dr_ds: f32 = w[20] * x3 * x5 * x6 / s.powi(2);
    let dr_dw20: f32 = x5 * (-t * x0 * x1 * x2 * x6 - x4.ln());
    (r_val, dr_ds, dr_dw20)
}

/// Difficulty update with mean reversion (before clamp).
/// Returns (D_new_unclamped, dD/dD_prev, dD/dw[0..21])
fn difficulty_update_grad(w: &[f32; 21], d: f32, r: f32) -> (f32, f32, [f32; 21]) {
    let x0: f32 = (3.0_f32 * w[5]).exp();
    let x1: f32 = w[4] - x0 + 1.0_f32;
    let x2: f32 = 1.0_f32 - w[7];
    let x3: f32 = (10.0_f32 / 9.0_f32) - (1.0_f32 / 9.0_f32) * d;
    let x4: f32 = r - 3.0_f32;
    let x5: f32 = w[6] * x4;
    let x6: f32 = x3 * x5;

    let d_new: f32 = w[7] * x1 + x2 * (d - x6);
    let dd_dd: f32 = x2 * ((1.0_f32 / 9.0_f32) * x5 + 1.0_f32);
    let mut dd_dw = [0.0_f32; 21];
    dd_dw[4] = w[7];
    dd_dw[5] = -3.0_f32 * w[7] * x0;
    dd_dw[6] = -x2 * x3 * x4;
    dd_dw[7] = -d + x1 + x6;
    (d_new, dd_dd, dd_dw)
}

/// Init difficulty D_init(rating) and its gradients.
/// Returns (D_init, dD/dw[0..21])
fn init_difficulty_grad(w: &[f32; 21], r: f32) -> (f32, [f32; 21]) {
    let x0: f32 = r - 1.0_f32;
    let x1: f32 = (w[5] * x0).exp();

    let d_init: f32 = w[4] - x1 + 1.0_f32;
    let mut dd_dw = [0.0_f32; 21];
    dd_dw[4] = 1.0_f32;
    dd_dw[5] = -x0 * x1;
    (d_init, dd_dw)
}

/// Stability after success (rating 2) and its gradients.
fn stability_success_r2_grad(w: &[f32; 21], s: f32, d: f32, t: f32) -> (f32, f32, f32, [f32; 21]) {
    let x0: f32 = 11.0_f32 - d;
    let x1: f32 = s.powf(-w[9]);
    let x2: f32 = (9.0_f32 / 10.0_f32).ln() / w[20];
    let x3: f32 = (-x2).exp();
    let x4: f32 = x3 - 1.0_f32;
    let x5: f32 = (1.0_f32 / s);
    let x6: f32 = t * x5;
    let x7: f32 = x4 * x6 + 1.0_f32;
    let x8: f32 = x7.powf(-w[20]);
    let x9: f32 = 1.0_f32 - x8;
    let x10: f32 = (w[10] * x9).exp();
    let x11: f32 = x10 - 1.0_f32;
    let x12: f32 = w[8].exp();
    let x13: f32 = w[15] * x1 * x11 * x12;
    let x14: f32 = x0 * x13;
    let x15: f32 = x14 + 1.0_f32;
    let x16: f32 = (1.0_f32 / x7);
    let x17: f32 = x0 * x1 * x12;
    let x18: f32 = w[15] * x10;
    let x19: f32 = w[10] * x8;
    let x20: f32 = s * x14;
    let x21: f32 = s * x17;
    let x22: f32 = x18 * x21;

    let s_new: f32 = s * x15;
    let ds_ds: f32 =
        s * (-w[9] * x14 * x5 - t * w[20] * x16 * x17 * x18 * x19 * x4 / s.powi(2)) + x15;
    let ds_dd: f32 = -s * x13;
    let mut ds_dw = [0.0_f32; 21];
    ds_dw[8] = x20;
    ds_dw[9] = -x20 * s.ln();
    ds_dw[10] = x22 * x9;
    ds_dw[15] = x11 * x21;
    ds_dw[20] = -x19 * x22 * (-x16 * x2 * x3 * x6 - x7.ln());
    (s_new, ds_ds, ds_dd, ds_dw)
}

/// Stability after success (rating 3) and its gradients.
fn stability_success_r3_grad(w: &[f32; 21], s: f32, d: f32, t: f32) -> (f32, f32, f32, [f32; 21]) {
    let x0: f32 = 11.0_f32 - d;
    let x1: f32 = s.powf(-w[9]);
    let x2: f32 = (9.0_f32 / 10.0_f32).ln() / w[20];
    let x3: f32 = (-x2).exp();
    let x4: f32 = x3 - 1.0_f32;
    let x5: f32 = (1.0_f32 / s);
    let x6: f32 = t * x5;
    let x7: f32 = x4 * x6 + 1.0_f32;
    let x8: f32 = x7.powf(-w[20]);
    let x9: f32 = 1.0_f32 - x8;
    let x10: f32 = (w[10] * x9).exp();
    let x11: f32 = w[8].exp();
    let x12: f32 = x1 * x11 * (x10 - 1.0_f32);
    let x13: f32 = x0 * x12;
    let x14: f32 = x13 + 1.0_f32;
    let x15: f32 = (1.0_f32 / x7);
    let x16: f32 = x0 * x1 * x10 * x11;
    let x17: f32 = w[10] * x8;
    let x18: f32 = s * x13;
    let x19: f32 = s * x16;

    let s_new: f32 = s * x14;
    let ds_ds: f32 = s * (-w[9] * x13 * x5 - t * w[20] * x15 * x16 * x17 * x4 / s.powi(2)) + x14;
    let ds_dd: f32 = -s * x12;
    let mut ds_dw = [0.0_f32; 21];
    ds_dw[8] = x18;
    ds_dw[9] = -x18 * s.ln();
    ds_dw[10] = x19 * x9;
    ds_dw[20] = -x17 * x19 * (-x15 * x2 * x3 * x6 - x7.ln());
    (s_new, ds_ds, ds_dd, ds_dw)
}

/// Stability after success (rating 4) and its gradients.
fn stability_success_r4_grad(w: &[f32; 21], s: f32, d: f32, t: f32) -> (f32, f32, f32, [f32; 21]) {
    let x0: f32 = 11.0_f32 - d;
    let x1: f32 = s.powf(-w[9]);
    let x2: f32 = (9.0_f32 / 10.0_f32).ln() / w[20];
    let x3: f32 = (-x2).exp();
    let x4: f32 = x3 - 1.0_f32;
    let x5: f32 = (1.0_f32 / s);
    let x6: f32 = t * x5;
    let x7: f32 = x4 * x6 + 1.0_f32;
    let x8: f32 = x7.powf(-w[20]);
    let x9: f32 = 1.0_f32 - x8;
    let x10: f32 = (w[10] * x9).exp();
    let x11: f32 = x10 - 1.0_f32;
    let x12: f32 = w[8].exp();
    let x13: f32 = w[16] * x1 * x11 * x12;
    let x14: f32 = x0 * x13;
    let x15: f32 = x14 + 1.0_f32;
    let x16: f32 = (1.0_f32 / x7);
    let x17: f32 = x0 * x1 * x12;
    let x18: f32 = w[16] * x10;
    let x19: f32 = w[10] * x8;
    let x20: f32 = s * x14;
    let x21: f32 = s * x17;
    let x22: f32 = x18 * x21;

    let s_new: f32 = s * x15;
    let ds_ds: f32 =
        s * (-w[9] * x14 * x5 - t * w[20] * x16 * x17 * x18 * x19 * x4 / s.powi(2)) + x15;
    let ds_dd: f32 = -s * x13;
    let mut ds_dw = [0.0_f32; 21];
    ds_dw[8] = x20;
    ds_dw[9] = -x20 * s.ln();
    ds_dw[10] = x22 * x9;
    ds_dw[16] = x11 * x21;
    ds_dw[20] = -x19 * x22 * (-x16 * x2 * x3 * x6 - x7.ln());
    (s_new, ds_ds, ds_dd, ds_dw)
}

/// Stability after failure (raw path) and its gradients.
fn stability_failure_raw_grad(w: &[f32; 21], s: f32, d: f32, t: f32) -> (f32, f32, f32, [f32; 21]) {
    let x0: f32 = s + 1.0_f32;
    let x1: f32 = x0.powf(w[13]);
    let x2: f32 = (9.0_f32 / 10.0_f32).ln() / w[20];
    let x3: f32 = (-x2).exp();
    let x4: f32 = x3 - 1.0_f32;
    let x5: f32 = t / s;
    let x6: f32 = x4 * x5 + 1.0_f32;
    let x7: f32 = x6.powf(-w[20]);
    let x8: f32 = 1.0_f32 - x7;
    let x9: f32 = d.powf(-w[12]) * (w[14] * x8).exp();
    let x10: f32 = x9 * (x1 - 1.0_f32);
    let x11: f32 = w[11] * x10;
    let x12: f32 = w[11] * x1 * x9;
    let x13: f32 = (1.0_f32 / x6);
    let x14: f32 = w[14] * x11 * x7;

    let s_new: f32 = x11;
    let ds_ds: f32 = w[13] * x12 / x0 - t * w[20] * x13 * x14 * x4 / s.powi(2);
    let ds_dd: f32 = -w[12] * x11 / d;
    let mut ds_dw = [0.0_f32; 21];
    ds_dw[11] = x10;
    ds_dw[12] = -x11 * d.ln();
    ds_dw[13] = x12 * x0.ln();
    ds_dw[14] = x11 * x8;
    ds_dw[20] = -x14 * (-x13 * x2 * x3 * x5 - x6.ln());
    (s_new, ds_ds, ds_dd, ds_dw)
}

/// Stability after failure (min path: S / exp(w17*w18)).
fn stability_failure_min_grad(w: &[f32; 21], s: f32) -> (f32, f32, [f32; 21]) {
    let x0: f32 = (-w[17] * w[18]).exp();
    let x1: f32 = s * x0;

    let s_new: f32 = x1;
    let ds_ds: f32 = x0;
    let mut ds_dw = [0.0_f32; 21];
    ds_dw[17] = -w[18] * x1;
    ds_dw[18] = -w[17] * x1;
    (s_new, ds_ds, ds_dw)
}

/// Short-term stability (unclamped sinc) and its gradients.
/// Returns (S_new, sinc, dS/dS_prev, dS/dw[0..21])
fn stability_short_term_grad(w: &[f32; 21], s: f32, r: f32) -> (f32, f32, f32, [f32; 21]) {
    let x0: f32 = s.powf(-w[19]);
    let x1: f32 = r + w[18] - 3.0_f32;
    let x2: f32 = (w[17] * x1).exp();
    let x3: f32 = x0 * x2;
    let x4: f32 = s * x3;

    let s_new: f32 = x4;
    let sinc_val: f32 = x3;
    let ds_ds: f32 = -w[19] * x3 + x0 * x2;
    let mut ds_dw = [0.0_f32; 21];
    ds_dw[17] = x1 * x4;
    ds_dw[18] = w[17] * x4;
    ds_dw[19] = -x4 * s.ln();
    (s_new, sinc_val, ds_ds, ds_dw)
}

// ═══════════════════════════════════════════════════════════
// Template functions (branching logic + BPTT)
// ═══════════════════════════════════════════════════════════

/// BCE loss and its gradient w.r.t. retrievability R.
/// Returns (loss, dL/dR)
fn bce_loss_grad(r: f32, label: f32, weight: f32) -> (f32, f32) {
    // Clamp r to avoid log(0) / division by zero
    let r_safe = r.clamp(1e-10, 1.0 - 1e-10);
    let loss = -(label * r_safe.ln() + (1.0 - label) * (1.0 - r_safe).ln()) * weight;
    let dl_dr = -(label / r_safe - (1.0 - label) / (1.0 - r_safe)) * weight;
    (loss, dl_dr)
}

/// Compute a single step of the FSRS model with analytical gradients.
///
/// Handles all branching: init, padding, short-term, failure, success.
/// Applies clamp masks to zero out gradients at boundaries (matching Burn).
///
/// # Arguments
/// * `w` - 21 FSRS parameters
/// * `s_prev` - Previous stability (output of last step, already clamped)
/// * `d_prev` - Previous difficulty (output of last step, already clamped)
/// * `delta_t` - Days since last review at this step
/// * `rating` - Rating at this step (0=padding, 1-4=actual)
/// * `is_first` - Whether this is the first step in the sequence (nth == 0)
fn step_grad(
    w: &[f32; 21],
    s_prev: f32,
    d_prev: f32,
    delta_t: f32,
    rating: u32,
    is_first: bool,
) -> StepGrads {
    // ── Padding: passthrough ──────────────────────────────────────────
    if rating == 0 {
        return StepGrads::passthrough(s_prev, d_prev);
    }

    // ── Input clamps (model.rs:151-152) ──────────────────────────────
    // For non-init steps, s_prev/d_prev are from previous step's output
    // clamp, so they're always within bounds → input clamp grad = 1.
    let s_c = s_prev.clamp(S_MIN, S_MAX);
    let d_c = d_prev.clamp(D_MIN, D_MAX);

    // ── Init case (first step, zero state) ───────────────────────────
    if is_first && s_prev == 0.0 {
        // S_init = w[rating - 1]  (table lookup, model.rs:127-129)
        let s_init = w[rating as usize - 1];

        // D_init(rating) = w[4] - exp(w[5]*(r-1)) + 1  (model.rs:131-132)
        let r_f = rating as f32;
        let (d_init, dd_dw_init) = init_difficulty_grad(w, r_f);

        // Output clamps
        let s_new = s_init.clamp(S_MIN, S_MAX);
        let d_new = d_init.clamp(D_MIN, D_MAX);
        let s_active = s_init > S_MIN && s_init < S_MAX;
        let d_active = d_init > D_MIN && d_init < D_MAX;

        let mut ds_dw = [0.0_f32; 21];
        if s_active {
            ds_dw[rating as usize - 1] = 1.0;
        }

        let mut dd_dw = [0.0_f32; 21];
        if d_active {
            dd_dw.copy_from_slice(&dd_dw_init);
        }

        return StepGrads {
            s_new,
            d_new,
            ds_ds: 0.0,
            ds_dd: 0.0,
            dd_dd: 0.0,
            ds_dw,
            dd_dw,
        };
    }

    // ── Difficulty update (shared for all non-init branches) ─────────
    // model.rs:168-169  next_difficulty + mean_reversion + clamp
    let r_f = rating as f32;
    let (d_unclamped, dd_dd_raw, mut dd_dw) = difficulty_update_grad(w, d_c, r_f);
    let d_new = d_unclamped.clamp(D_MIN, D_MAX);

    // Zero D grads at clamp boundaries (matching Burn)
    let d_active = d_unclamped > D_MIN && d_unclamped < D_MAX;
    let dd_dd = if d_active { dd_dd_raw } else { 0.0 };
    if !d_active {
        dd_dw = [0.0; 21];
    }

    // ── Stability branch selection ───────────────────────────────────
    let (s_unclamped, ds_ds_raw, ds_dd_raw, mut ds_dw) = if delta_t == 0.0 {
        // Short-term path (model.rs:111-119, 166)
        let (s_st, sinc_val, ds_ds_st, ds_dw_st) = stability_short_term_grad(w, s_c, r_f);

        if rating >= 2 && sinc_val < 1.0 {
            // clamp_min(sinc, 1.0) is active → S_new = S_prev, grad = 0
            // (Burn zeros the gradient when clamped, model.rs:118)
            (s_c, 1.0_f32, 0.0_f32, [0.0_f32; 21])
        } else {
            (s_st, ds_ds_st, 0.0_f32, ds_dw_st)
        }
    } else if rating == 1 {
        // Failure path (model.rs:95-109, 165)
        let (s_raw, ds_ds_raw, ds_dd_raw, ds_dw_raw) =
            stability_failure_raw_grad(w, s_c, d_c, delta_t);
        let (s_min, ds_ds_min, ds_dw_min) = stability_failure_min_grad(w, s_c);

        if s_min < s_raw {
            // min path active: use S_fail_min
            (s_min, ds_ds_min, 0.0_f32, ds_dw_min)
        } else {
            // raw path active: use S_fail_raw
            (s_raw, ds_ds_raw, ds_dd_raw, ds_dw_raw)
        }
    } else {
        // Success path (model.rs:71-93, 164-165)
        match rating {
            2 => stability_success_r2_grad(w, s_c, d_c, delta_t),
            3 => stability_success_r3_grad(w, s_c, d_c, delta_t),
            4 => stability_success_r4_grad(w, s_c, d_c, delta_t),
            _ => unreachable!(),
        }
    };

    // ── Output S clamp (model.rs:188) ────────────────────────────────
    let s_new = s_unclamped.clamp(S_MIN, S_MAX);
    let s_active = s_unclamped > S_MIN && s_unclamped < S_MAX;
    let ds_ds = if s_active { ds_ds_raw } else { 0.0 };
    let ds_dd = if s_active { ds_dd_raw } else { 0.0 };
    if !s_active {
        ds_dw = [0.0; 21];
    }

    StepGrads {
        s_new,
        d_new,
        ds_ds,
        ds_dd,
        dd_dd,
        ds_dw,
        dd_dw,
    }
}

/// Full forward-backward pass (BPTT) for a single training example.
///
/// Processes a sequence of reviews and computes the analytical gradient
/// of the BCE loss with respect to all 21 FSRS parameters.
///
/// This is mathematically equivalent to:
///   model.forward_classification() + loss.backward()
/// from src/training.rs (with Reduction::Sum, single item).
///
/// # Arguments
/// * `w` - 21 FSRS parameters
/// * `delta_ts` - Review history: days since last review at each step
/// * `ratings` - Review history: rating (1-4) at each step, 0 for padding
/// * `final_delta_t` - Days elapsed for the current (evaluated) review
/// * `label` - Ground truth: 1.0 if recalled, 0.0 if forgotten
/// * `weight` - Sample weight for the loss
///
/// # Returns
/// `(loss, grad_w)` where `grad_w[i]` = ∂loss/∂w\[i\]
pub fn forward_backward(
    w: &[f32; 21],
    delta_ts: &[f32],
    ratings: &[u32],
    final_delta_t: f32,
    label: f32,
    weight: f32,
) -> (f32, [f32; 21]) {
    let n = delta_ts.len();
    assert_eq!(n, ratings.len());

    // ── Forward pass: compute intermediate states + store Jacobians ───
    let mut s_states = Vec::with_capacity(n + 1);
    let mut d_states = Vec::with_capacity(n + 1);
    s_states.push(0.0_f32);
    d_states.push(0.0_f32);

    let mut step_results: Vec<StepGrads> = Vec::with_capacity(n);

    for k in 0..n {
        let sg = step_grad(w, s_states[k], d_states[k], delta_ts[k], ratings[k], k == 0);
        s_states.push(sg.s_new);
        d_states.push(sg.d_new);
        step_results.push(sg);
    }

    // ── Final retrievability and loss ────────────────────────────────
    let s_final = s_states[n];
    let (r_final, dr_ds, dr_dw20) = forgetting_curve_grad(w, final_delta_t, s_final);
    let (loss, dl_dr) = bce_loss_grad(r_final, label, weight);

    // ── Backward pass: accumulate gradients via BPTT ─────────────────
    let mut grad_w = [0.0_f32; 21];

    // Adjoints: dL/dS_N and dL/dD_N
    let mut adj_s = dl_dr * dr_ds;
    let mut adj_d = 0.0_f32; // Loss doesn't depend directly on D_final

    // Direct gradient of w[20] through the final forgetting curve
    grad_w[20] += dl_dr * dr_dw20;

    // Backpropagate through the sequence
    for k in (0..n).rev() {
        let sg = &step_results[k];

        // Accumulate parameter gradients at this step
        for (i, grad) in grad_w.iter_mut().enumerate() {
            *grad += adj_s * sg.ds_dw[i] + adj_d * sg.dd_dw[i];
        }

        // Propagate adjoints to previous step
        // Note: dD/dS = 0 always (difficulty doesn't depend on stability)
        let new_adj_s = adj_s * sg.ds_ds; // + adj_d * 0
        let new_adj_d = adj_s * sg.ds_dd + adj_d * sg.dd_dd;
        adj_s = new_adj_s;
        adj_d = new_adj_d;
    }

    (loss, grad_w)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Reference test data from src/training.rs test_loss_and_grad.
    /// Uses DEFAULT_PARAMETERS and specific batch data.
    #[test]
    fn test_analytical_gradient_matches_burn() {
        // DEFAULT_PARAMETERS from inference.rs
        let w: [f32; 21] = [
            0.212, 1.2931, 2.3065, 8.2956, 6.4133, 0.8334, 3.0194, 0.001, 1.8722, 0.1666, 0.796,
            1.4835, 0.0614, 0.2629, 1.6483, 0.6014, 1.8729, 0.5425, 0.0912, 0.0658, 0.1542,
        ];

        // Test batch from test_loss_and_grad (4 items, 6 timesteps each)
        // t_historys[step][item]:
        let t_historys: [[f32; 4]; 6] = [
            [0.0, 0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
            [0.0, 1.0, 1.0, 3.0],
            [1.0, 3.0, 3.0, 5.0],
            [3.0, 6.0, 6.0, 12.0],
        ];
        // r_historys[step][item]:
        let r_historys: [[u32; 4]; 6] = [
            [1, 2, 3, 4],
            [3, 4, 2, 4],
            [1, 4, 4, 3],
            [4, 3, 3, 3],
            [3, 1, 3, 3],
            [2, 3, 3, 4],
        ];
        let delta_ts: [f32; 4] = [4.0, 11.0, 12.0, 23.0];
        let labels: [f32; 4] = [1.0, 1.0, 1.0, 0.0];
        let weights: [f32; 4] = [1.0, 1.0, 1.0, 1.0];

        // Expected gradient from Burn (from test_loss_and_grad)
        let expected_grad: [f32; 21] = [
            -0.095688485,
            -0.0051607806,
            -0.0012249565,
            0.007462064,
            0.03650761,
            -0.082112335,
            0.0593964,
            -2.1474836,
            0.57626534,
            -2.8751316,
            0.7154875,
            -0.028993709,
            0.0099172965,
            -0.2189217,
            -0.0017800558,
            -0.089381434,
            0.299141,
            0.068104014,
            -0.011605468,
            -0.25398168,
            0.27700496,
        ];

        // Compute analytical gradients for all 4 items and sum
        let mut total_loss = 0.0_f32;
        let mut total_grad = [0.0_f32; 21];

        for item in 0..4 {
            let item_delta_ts: Vec<f32> = (0..6).map(|step| t_historys[step][item]).collect();
            let item_ratings: Vec<u32> = (0..6).map(|step| r_historys[step][item]).collect();

            let (loss, grad) = forward_backward(
                &w,
                &item_delta_ts,
                &item_ratings,
                delta_ts[item],
                labels[item],
                weights[item],
            );
            total_loss += loss;
            for i in 0..21 {
                total_grad[i] += grad[i];
            }
        }

        // Expected total loss
        let expected_loss = 4.0466027_f32;
        let loss_err = (total_loss - expected_loss).abs();
        assert!(
            loss_err < 1e-4,
            "Loss mismatch: got {total_loss}, expected {expected_loss}, err={loss_err}"
        );

        // Check gradient match
        for i in 0..21 {
            let err = (total_grad[i] - expected_grad[i]).abs();
            let rel = if expected_grad[i].abs() > 1e-8 {
                err / expected_grad[i].abs()
            } else {
                err
            };
            assert!(
                err < 1e-3 || rel < 1e-2,
                "Gradient mismatch at w[{i}]: got {}, expected {}, abs_err={err}, rel_err={rel}",
                total_grad[i],
                expected_grad[i]
            );
        }
    }
}
